#!/bin/bash
# Program that gets what packages were installed by the user through apt-get

echo "Note: Data may not be reliable!"
zgrep -Pho '(?<=apt-get install ).*' /var/log/apt/history.log.*.gz | tr ' ' $'\n' | sort -u
