#!/bin/bash
# Modifies your mac address using macchanger
# Programmed by CoolCat467.

# VERSION 1.0.0

# Interface that this program acts appon
VINTERFACE="wlp1s0"

## VARIABLE SETUP ##
VArgz="False"
VFlagPerm=0
VFlagRand=0
VFlagSupp=0
VFlagHelp=0
VSudoed="False"
VCommand=""


## FUNCTIONS ###
function AuthSudo {
	#echo "Please enter the sudo password to continue." &&
	[[ "$VSudoed" != "True" ]] &&
	sudo -v &&
	VSudoed="True"
}

function menu {
	### WELCOME SCREEN ###
	clear
	echo "Welcome to the mac changer screen!"
	echo ""
	echo "1. - Set mac address to default"
	echo "2. - Set mac address to random"
	echo "3. - Set mac address to supplied"
	echo "4. - Close"
	echo ""
	echo -n "Please enter an option and press RETURN: "
	read input
	choose
}

function choose {
	### MENU INPUT ###

	# INPUT ERROR
	[[ "$input" != "1" ]] &&
		[[ "$input" != "2" ]] &&
			[[ "$input" != "3" ]] &&
				[[ "$input" != "4" ]] &&
					clear &&
					echo "Please enter the numeric value of the option." &&
					echo "(press RETURN to continue)" &&
					read &&
					menu
	# VALID INPUT
	echo ""
	[[ "$input" = "1" ]] && default
	[[ "$input" = "2" ]] && rand
	[[ "$input" = "3" ]] && menuSet
	[[ "$input" = "4" ]] && quit
}

function default {
	VCommand='-p'
	run
}

function rand {
	VCommand='-r'
	run
}

function menuSet {
	echo -n "Please enter mac address: "
	read input &&
	VCommand='--mac='$input &&
	echo "" &&
	run
}

function set {
	[[ "VCommand" != "" ]] &&
	VCommand='--mac='$VCommand &&
	run
}

function run {
	AuthSudo
	sudo ifconfig $VINTERFACE down &&
	sudo macchanger $VCommand $VINTERFACE &&
	sudo ifconfig $VINTERFACE up
}

function DisplayOptions {
	echo "Usage:"
	echo "  update [-d, -r, -s, -h] <MAC ADDRESS>"
	echo "    -d : Set mac address to default"
	echo "    -r : Set mac address to random"
	echo "    -s : Set mac address to <MAC ADDRESS>"
	echo "    -h, -help, --help : Show this message"
	echo
	echo "Created by CoolCat467"
}

function quit {
	exit 0
}

function main {
	[[ "$VFlagPerm" = "1" ]] && default
	[[ "$VFlagRand" = "1" ]] && rand
	[[ "$VFlagSupp" = "1" ]] && set
	[[ "$VFlagHelp" = "1" ]] && DisplayOptions
	[[ "$VArgz" != "True" ]] && menu
}

### MAIN ###
[[ "$1" = "-d" ]] && VFlagPerm=1 && VArgz="True"
[[ "$1" = "-r" ]] && VFlagRand=1 && VArgz="True"
[[ "$1" = "-s" ]] && VFlagSupp=1 && VCommand="$2" && VArgz="True"

[[ "$1" = "-h" ]] && VFlagHelp=1 && VArgz="True"
[[ "$1" = "-help" ]] && VFlagHelp=1 && VArgz="True"
[[ "$1" = "--help" ]] && VFlagHelp=1 && VArgz="True"

main
