#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Use pygame to play a midi file

"Play a midi file."

import os
import time

import pygame.mixer

def run(args):
    "Load music file and play it until it's over or keyboard interrupt."
    if not args:
        return
    file = os.path.abspath(args[0])
    pygame.mixer.music.load(file)
    pygame.mixer.music.play()
    try:
        while pygame.mixer.music.get_busy():
            time.sleep(1)
    except KeyboardInterrupt:
        pass
    pygame.mixer.music.stop()


if __name__ == '__main__':
    pygame.mixer.init()
    try:
        run(os.sys.argv[1:])
    finally:
        pygame.quit()
